import type { PolicyAction, PolicyReason } from './types.js';

// Metadata-only audit entry. Captures enough context to debug a decision
// post-mortem (event kind, peer, group, size, decision, reason, time)
// WITHOUT carrying any plaintext, ciphertext, key bytes, or other
// content-bearing material.
//
// Privacy invariant: every field on this type must be safe to log,
// serialize over MCP, persist to disk, or include in a public-ish debug
// dump. New fields require explicit review against that invariant.
export interface PolicyAuditEntry {
  // Audit row id — generated by the audit log, not by the policy itself.
  auditId: string;
  // Wall-clock receipt time, supplied by the gate.
  receivedAt: number;
  // Event metadata — all optional because malformed events may lack any
  // of these fields. Always metadata-only when present.
  eventKind: 'group' | 'dm' | 'unknown';
  messageId?: string;
  groupIdHex?: string;
  senderFingerprint?: string;
  // Length of the (decrypted) plaintext payload in bytes. Reveals message
  // size only — not content. 0 when no plaintext is available
  // (malformed-event, etc.).
  byteLength: number;
  // Policy outcome.
  action: PolicyAction;
  reason: PolicyReason;
  // Decision detail. Defaults to false / [] for fail-closed paths so the
  // shape stays uniform.
  addressedToMe: boolean;
  senderTrusted: boolean;
  matchedInterests: string[];
  // True when the gate itself rejected before AgentPolicy.decide() ran
  // (validation failed, duplicate, non-member). Useful to distinguish
  // pure-policy decisions from structural/auth rejections.
  gateRejected: boolean;
}

// Helper to summarize a Uint8Array's length without exposing any byte. Use
// in any new code path that handles plaintext/ciphertext/keys.
export function redactPlaintext(bytes: Uint8Array | undefined): { byteLength: number } {
  return { byteLength: bytes ? bytes.byteLength : 0 };
}
